openapi: "3.0.2"
info:
  title: Vant API
  version: "1.0.0"
servers:
  - url: http://localhost:8000/api/v1
    description: Development server
  - url: https://harrystation.de:8000/api/v1
    description: Production server
components:
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: x-api-key
security:
  - api_key: []
paths:
  /records/latest:
    $ref: "./paths/records/latest/path.yml"
  /records:
    $ref: "./paths/records/path.yml"
  /records/{element}/latest:
    $ref: "./paths/records/{element}/latest/path.yml"
  /records/{element}:
    $ref: "./paths/records/{element}/path.yml"
  /dwd-warnings:
    $ref: "./paths/dwd-warnings/path.yml"
  /meteomatics/forecast:
    $ref: "./paths/meteomatics/forecast/path.yml"
  /meteomatics/live:
    $ref: "./paths/meteomatics/live/path.yml"
  /config:
    $ref: "./paths/config/path.yml"
  /config/generate-api-key:
    $ref: "./paths/config/generate-api-key/path.yml"
  /highs-lows:
    $ref: "./paths/highs-lows/path.yml"
  /climate:
    $ref: "./paths/climate/path.yml"
