version: "3"
services:
  api:
    image: vant-api
    ports:
      -  8000:8000
    privileged: true
    volumes:
      - type: bind
        source: /dev
        target: /dev
      - type: bind
        source: /run/udev
        target: /run/udev:ro
    links:
      - mongodb
  mongodb:
    image: mongo:4.4.18
    command: mongod --quiet --logpath /dev/null
    ports:
      - 27017:27017
    volumes:
      - type: bind
        source: ./data
        target: /data/db